### ISSUE TITLE
Not working due to multiple errors

### ISSUE THREAD

**Issue by davidrot** [jiangfengming/svelte-vite-ssr#2]
Hi,

i was trying to execute your code, but sadly it was not working. After adjusting the environment variables in the package.json for dev:ssr and accessing the page I have found following errors in the console.

I just thought I would tell you and thank you in advance for your great work. :)

```
$ SET VITE_SVELTE_HYDRATABLE=1 PORT=3000 && node ssr-dev-server
Pre-bundling dependencies:
  svelte-pilot
(this will be run only when your dependencies or config have changed)
http://localhost:3000
22:47:47 [vite] Error when evaluating SSR module /src/server-render.ts:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\svelte-pilot\dist\index.js
require() of ES modules is not supported.
require() of C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\svelte-pilot\dist\index.js from C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\vite\dist\node\chunks\dep-972722fa.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\svelte-pilot\package.json.

    at new NodeError (node:internal/errors:363:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:13)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at nodeRequire (C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\vite\dist\node\chunks\dep-972722fa.js:73811:17)
    at ssrImport (C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\vite\dist\node\chunks\dep-972722fa.js:73753:20)
    at eval (/src/server-render.ts:3:37)
    at instantiateModule (C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\vite\dist\node\chunks\dep-972722fa.js:73796:15)
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\svelte-pilot\dist\index.js
require() of ES modules is not supported.
require() of C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\svelte-pilot\dist\index.js from C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\vite\dist\node\chunks\dep-972722fa.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\svelte-pilot\package.json.

    at new NodeError (node:internal/errors:363:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:13)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at nodeRequire (C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\vite\dist\node\chunks\dep-972722fa.js:73811:17)
    at ssrImport (C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\vite\dist\node\chunks\dep-972722fa.js:73753:20)
    at eval (/src/server-render.ts:3:37)
    at instantiateModule (C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\node_modules\vite\dist\node\chunks\dep-972722fa.js:73796:15) {
  code: 'ERR_REQUIRE_ESM'
}
TypeError: render is not a function
    at Immediate.<anonymous> (C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\ssr-dev-server.js:32:56)
Unrestricted file system access to "/service-worker.js"
For security concerns, accessing files outside of serving allow list will be restricted by default in the future version of Vite. Refer to https://vitejs.dev/config/#server-fs-allow for more details.
TypeError: render is not a function
    at Immediate.<anonymous> (C:\Users\David\dev\ssr\svelte-vite-ssr-demo-main\ssr-dev-server.js:32:56)
```

**Comment by davidrot** [comment]
It looks like it is related due to windows. It is running in my linux vm, but still wondering why it is not working on windows.

**Comment by jiangfengming** [comment]
What shell are you using? WSL or git-bash Maybe works.
